### PR TITLE
Clean up documenting norms

### PR DESCRIPTION
**Pull request by berwinlan**
whoops didn't see that this had been closed, just added our docs in separate files and reorged some stuff

### CODE REVIEW

**Review by hnvakil — APPROVED** [review]
This all looks good to me, thanks for writing this up Berwin!

**Comment by hnvakil** [comment]
Wait, not green head! What if this fails tests??

haha hi -berwin

**Comment by berwinlan** [comment]
> Wait, not green head! What if this fails tests??
> 
> haha hi -berwin

so true! resolved, switched to true head

**Comment by hnvakil** [comment]
Phew! Glad it's going to the right place now 😌

**Pull request merged**
