### PR TITLE
Precommit hook work

### PR DESCRIPTION
**Pull request by hnvakil**

### CODE REVIEW

**Review by benmor20 — CHANGES_REQUESTED** [review]
Remove the pycache files (and probably want to fix the gitignore)

**Comment by hnvakil** [comment]
Okay I have done the requested changes @benmor20

**Review by berwinlan — APPROVED** [review]
Looks great, Han!

**Review by benmor20 — APPROVED** [review]
Looks good!

**Comment by hnvakil** [comment]
Merging into wrong branch, closing

**Pull request closed without merging**
